### ISSUE TITLE
Issue with multi-sourcing a single product from multiple predecessors

### ISSUE THREAD

**Issue by bruskey47** [LarrySnyder/stockpyl#171]
When a node has multiple predecessors with the same raw material, there are issues with the output. For example when running:

network = network_from_edges(
edges=[(2, 1), (3, 1)],
node_order_in_lists=[1, 2, 3],
local_holding_cost=[2,4,2],
stockout_cost=[50, 25, 25],
demand_type='UD', # discrete uniform distribution, for easier debugging
lo=1,
hi=5,
shipment_lead_time=[0, 0, 0],
order_lead_time=[0, 0, 0]
)

nodes = {n.index: n for n in network.nodes}

products = {10: SupplyChainProduct(index=10), 20: SupplyChainProduct(index=20)}
products[10].set_bill_of_materials(raw_material=20, num_needed=3)

nodes[1].add_product(products[10])
nodes[2].add_product(products[20])
nodes[3].add_product(products[20])

products[10].inventory_policy = Policy(type='BS', base_stock_level=10, node=nodes[1], product=products[10])
nodes[2].inventory_policy = {20: Policy(type='BS', base_stock_level=12, node=nodes[2], product=products[20])}
nodes[3].inventory_policy = {20: Policy(type='BS', base_stock_level=22, node=nodes[3], product=products[20])}

total_cost = simulation(network, 100, rand_seed=17)

...the output has problems. Firstly, in the first time period, 6 units of product 20 are ordering by node 1 to _both_ nodes 2 and 3. Under the new multiproduct code, it shouldn't have to order from both nodes. Also, the units are shipped to node 1 immediately, but there is a 1-period delay between the order and its shipment, even though all lead times are set to 0.

**Comment by LarrySnyder** [comment]
@bruskey47 Great catch. There were two bugs, and two fixes.

The duplicate order (6 units of product 20 from _both_ node 1 and node 2) was caused by a bug in `policy.py`. The policy just ordered the same quantity from every supplier. So I created a dict called `still_to_order` that indicates the amount left to order for each RM, and that amount gets reduced each time we place an order to the supplier. (For now, this just means that `still_to_order` goes to 0 after we order from the first supplier, and then we don't order from subsequent suppliers. But I made it a little more flexible so in the future we can handle things like alternate policies, or per-supplier ordering capacities.) The new code is:

https://github.com/LarrySnyder/stockpyl/blob/1a9be4d29d683df0ecad1d53a6f688793d27da89/src/stockpyl/policy.py#L499-L519

The second bug, the inbound shipment delay, was caused by sloppy logic in `sim._generate_downstream_shipments()`. It used to be that, after processing the inbound shipments at a node and converting RM to FG, we immediately call the downstream node to do the same. But we can't do it that way; we have to wait until _all_ of the downstream node's successors have been processed, not just one. Here's the fix:

https://github.com/LarrySnyder/stockpyl/blob/1a9be4d29d683df0ecad1d53a6f688793d27da89/src/stockpyl/sim.py#L504-L508

To test that these fixes work, please replace your test code with the following. (Note that I'm creating a new type of policy, which splits the orders evenly among all suppliers for a given RM.) Make sure the output looks right to you. If it does, you can close this issue.

```py
from stockpyl.supply_chain_network import network_from_edges
from stockpyl.supply_chain_product import SupplyChainProduct
from stockpyl.policy import Policy
from stockpyl.sim import simulation
from stockpyl.sim_io import write_results

network = network_from_edges(
edges=[(2, 1), (3, 1)],
node_order_in_lists=[1, 2, 3],
local_holding_cost=[2,4,2],
stockout_cost=[50, 25, 25],
demand_type='UD', # discrete uniform distribution, for easier debugging
lo=1,
hi=5,
shipment_lead_time=[0, 0, 0],
order_lead_time=[0, 0, 0]
)

nodes = {n.index: n for n in network.nodes}

products = {10: SupplyChainProduct(index=10), 20: SupplyChainProduct(index=20)}
products[10].set_bill_of_materials(raw_material=20, num_needed=3)

nodes[1].add_product(products[10])
nodes[2].add_product(products[20])
nodes[3].add_product(products[20])

class MultisourcePolicy(Policy):
	def __init__(self, **kwargs):
		super().__init__(**kwargs)

	def get_order_quantity(self, product=None, order_capacity=None, include_raw_materials=False, inventory_position=None, echelon_inventory_position_adjusted=None):
		OQ_dict = super().get_order_quantity(product, order_capacity, include_raw_materials, inventory_position, echelon_inventory_position_adjusted)
		if isinstance(OQ_dict, dict):
			for rm_ind in self.node.raw_materials_by_product(product=None, return_indices=True, network_BOM=False):
				# Shortcut to suppliers for this RM.
				supp_inds = self.node.raw_material_suppliers_by_raw_material(raw_material=rm_ind, return_indices=True, network_BOM=False)
				# Get total order quantity for this RM.
				total_OQ = sum([OQ_dict[supp_ind][rm_ind] for supp_ind in supp_inds])
				# Split order evenly across suppliers.
				for supp_ind in supp_inds:
					OQ_dict[supp_ind][rm_ind] = total_OQ / len(supp_inds)
		return OQ_dict

products[10].inventory_policy = MultisourcePolicy(type='BS', base_stock_level=10, node=nodes[1], product=products[10])
nodes[2].inventory_policy = {20: Policy(type='BS', base_stock_level=12, node=nodes[2], product=products[20])}
nodes[3].inventory_policy = {20: Policy(type='BS', base_stock_level=22, node=nodes[3], product=products[20])}

total_cost = simulation(network, 100, rand_seed=17)
write_results(network, num_periods=10, columns_to_print=['basic', 'costs', 'RM'], write_txt=True, txt_filename='debugging_files/issue171_output.txt')
```

**Comment by bruskey47** [comment]
It looks like your changes fixed this issue. The above code, and my original code, both run without issue, and the output looks consistent with what you'd expect. Thanks!
