### ISSUE TITLE
Issue with shipment-pausing (SP) disruptions and nodes with external supply

### ISSUE THREAD

**Issue by bruskey47** [LarrySnyder/stockpyl#172]
When a node with external supply has a shipment-pausing disruption, it doesn't appear that shipments to it actually get paused. I know that the imaginary "external supply" node doesn't have an "outbound disrupted items" count, but I think you'd still expect the real node to not receive shipment given the definition of an SP disruption. For all other nodes, the SP type seems to be working as expected. 

Here is the code I ran:

network = network_from_edges(
edges=[(2, 1)],
node_order_in_lists=[1, 2],
local_holding_cost=[100,25],
stockout_cost=0,
demand_type='D', # discrete uniform distribution, for easier debugging,
demand_list = [2, 2, 2, 1, 0, 2, 2, 1, 3, 2],
order_capacity = [2,20],
shipment_lead_time=0,
order_lead_time=0
)

nodes = {n.index: n for n in network.nodes}

products = {10: SupplyChainProduct(index=10), 20: SupplyChainProduct(index=20)}
products[20].set_bill_of_materials(raw_material=10, num_needed=0.5)

nodes[1].add_product(products[20])
nodes[2].add_product(products[10])
nodes[2].initial_inventory_level = 10
nodes[1].initial_inventory_level = 10

products[20].inventory_policy = Policy(type='rQ', reorder_point = 10e5, order_quantity = 2, node=nodes[1], product=products[20])
products[10].inventory_policy = Policy(type='rQ', reorder_point = 10e2, order_quantity = 1, node=nodes[2], product=products[10])

network.get_node_from_index(2).disruption_process = DisruptionProcess(
            random_process_type='E',
            disruption_type='SP',
            disruption_state_list=[False, False, True, False, False, False, False, True, True, False]
        )

simulation(network=network, num_periods=10, rand_seed=16, progress_bar=False)
write_results(network=network, num_periods=10)

The results show that at every time period, node 2 receives 1 unit of the dummy product, shipped from the external supplier - even during the disrupted periods.

**Comment by LarrySnyder** [comment]
@bruskey47 I think this is expected (although not particularly well documented) behavior. I guess my assumption was that external suppliers can't be disrupted. Or maybe a more honest way to say it is: I didn't implement SP disruptions for nodes with external suppliers because you can accomplish the same thing using OP disruptions, at least if the order lead time is 0. That's because the order to and the shipment from the external supplier happen simultaneously, so pausing orders is the same as pausing shipments.

I can see why the behavior you expected is more natural though. It would be a pain to implement this in the current code (because SP disruptions are handled at the shipping node, not the receiving node, and there _is_ not shipping node if it's an external supplier). But if this is relatively easy to implement in the refactor, then you all should go for it. We can address the discrepancies between the outputs of the v1 vs v2 simulations manually for this specific use case.
